### ISSUE TITLE
LoadError when using Sequel mixin for models

### ISSUE THREAD

**Issue by correiarmjoao** [omniauth/omniauth-identity#112]
When trying to use the sequel mixin inside a sequel model, the following error is happening.
```
LoadError: no such file to load -- nobrainer
                            require at org/jruby/RubyKernel.java:974
                             <main> at /Users/joaocorreia/.rvm/gems/jruby-9.2.11.1/gems/omniauth-identity-3.0.8/lib/omniauth/identity/models/sequel.rb:3
```
Looking at the code nobrainer is being required instead of sequel

https://github.com/omniauth/omniauth-identity/blob/950235650087ec8431513e66f278ad260e5c9e10/lib/omniauth/identity/models/sequel.rb#L3-L12

**Comment by pboling** [comment]
Oops!!  Thanks for finding that.  In the spec suite everything is loaded, so this kind of bug it hard to find via unit testing. :)

**Comment by pboling** [comment]
Fixed by https://github.com/omniauth/omniauth-identity/commit/a320b38b68961c67167bf3f3059d008015e92223

Will release a patched gem soon.

**Comment by pboling** [comment]
Version 3.0.9 released with fix @correiarmjoao
