### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by aarondmills** [omniauth/omniauth-identity#12]
I have attempted to create a password reset process for users that make a mistake on signup, or forget their password. It seems though that simply updating the attributes of the identity model where the password is stored does not work. 

Does anyone have a good solution for this?

**Comment by pboling** [comment]
```
@identity = Identity.find(1)
@identity.password = "newpassword"
@identity.password_confirmation = "newpassword"
@identity.save
```

Should work.  Closing.  If still an issue please write a failing spec!
