### ISSUE TITLE
Prevent unauthenticated user from registering new user

### ISSUE THREAD

**Issue by ianmiller** [omniauth/omniauth-identity#14]
This is probably a shortcoming on my part, but I can't figure out how to prevent an unauthenticated user from accessing the /auth/identity/register route.

This is necessary in any application where access is not intended to be "open", and an administrator (or any other specific role) is required to create an account. Any application intended to serve a small community on an invitation-only basis needs this functionality.

**Comment by pboling** [comment]
Fixed in #21
