### ISSUE TITLE
Access identity object in case of login failure

### ISSUE THREAD

**Issue by jayandra** [omniauth/omniauth-identity#23]
I am struggling to access the identity object in case of failed login inside my SessionsController#failure action. 

I was wondering if it is possible to be accessed as in IdentitiesController#new action ( env['omniauth.identity'] ).

**Comment by petrsigut** [comment]
@jayandra have you find any solution? We need the access the auth_key (email) when user fail to login/signup...

**Comment by pboling** [comment]
This should now be available in the latest release.
