### ISSUE TITLE
Custom fields breaking registration?

### ISSUE THREAD

**Issue by pareeohnos** [omniauth/omniauth-identity#35]
Hey,

I'm having a big problem trying to add additional fields to the registration process where it somewhere losing the email address internally?

If I leave everything as standard, then the registration works perfectly. Now I want to add a date of birth, and gender field to the process, so in my omniauth confi, I've added 

``` ruby
provider :identity, fields: [:name, :email, :gender, :dob_year, :dob_month, :dob_day]
```

And that's fine, if I load the default registration form provided by omniauth-identity they show up, but when I then try and register I have issues. It appears to create the Identity on the database itself which is great, but then when it attempts to retrieve the Identity (I assume to login) I see the following in the logs :

``` ruby
Started POST "/auth/identity/register" for 127.0.0.1 at 2012-08-08 13:47:12 +0100
   (13.3ms)  SELECT 1 FROM "identities" WHERE "identities"."email" = 'abcd@abcd.com' LIMIT 1
Binary data inserted for `string` type on column `password_digest`
  SQL (39.7ms)  INSERT INTO "identities" ("created_at", "dob_day", "dob_month", "dob_year", "email", "gender", "name", "password_digest", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)  [["created_at", Wed, 08 Aug 2012 12:47:13 UTC +00:00], ["dob_day", 9], ["dob_month", 2], ["dob_year", 1989], ["email", "abcd@abcd.com"], ["gender", "Male"], ["name", "tester"], ["password_digest", "$2a$10$1apvNK5SKO.0TiOUByRfQ.Ul8NXRkLIErtiDjPtI7DtnFKK7GL8Pe"], ["updated_at", Wed, 08 Aug 2012 12:47:13 UTC +00:00]]
(identity) Callback phase initiated.
  Identity Load (0.3ms)  SELECT "identities".* FROM "identities" WHERE "identities"."email" IS NULL LIMIT 1
(identity) Authentication failure! invalid_credentials encountered.
```

It then redirects me back to my login screen. I can then login and it's fine, but I need the redirect after registration to work.
Any reason this is happening?

I have added the fields to my Identity model with 

``` ruby
attr_accessible :name, :email, :password, :password_confirmation, :dob_year, :dob_month, :dob_day, :gender
```

I am really stumped and cannot figure out what's causing this. Please can someone help?

**Comment by pboling** [comment]
You can only define the `provider` macro one time for each distinct `provider`.  You can only define one "facebook" provider, and one "google" provider, etc.  Same with "identity".
