### ISSUE TITLE
To associate or not to associate

### ISSUE THREAD

**Issue by dlee** [omniauth/omniauth-identity#36]
The README says:

> OmniAuth Identity is different from many other user authentication systems in that it is not intended to be associated with your primary User model. Instead, the Identity model should be associated with your User model..

That sounds contradictory and should be reworded.

**Comment by pboling** [comment]
Good call.  The note was fixed at some point in history. :). It now reads:

> **Note:** OmniAuth Identity is different from many other user authentication
systems in that it is *not* built to store authentication information in your primary
`User` model. Instead, the `Identity` model should be **associated** with your
`User` model giving you maximum flexibility to include other authentication
strategies such as Facebook, Twitter, etc.
