### ISSUE TITLE
Purpose of auth_key= in model adapters is unclear

### ISSUE THREAD

**Issue by tpope** [omniauth/omniauth-identity#42]
All the model adapters feature an override of `auth_key=` that looks something like this:

```
        def self.auth_key=(key)
          super
          validates_uniqueness_of key, :case_sensitive => false
        end
```

Problem is, there's no superclass method, so this blows up if you try to actually call it. Is this supposed to be patching the `auth_key` method instead?

**Comment by pboling** [comment]
This is fixed.  Please try latest release!
