### ISSUE TITLE
Remove password validations

### ISSUE THREAD

**Issue by paulspringett** [omniauth/omniauth-identity#43]
[This line here](https://github.com/intridea/omniauth-identity/blob/master/lib/omniauth/identity/secure_password.rb#L46) forces a validation on the `password_digest` attribute, which outputs silly validation errors like

> Password digest can't be blank

No normal user knows what a password digest is. As it's not possible to remove validations once they are added, I propose you simply remove the validations altogether. Leave it up to the developer to enforce their own validations.

**Comment by pboling** [comment]
The answer given was great.  Closing.
