### ISSUE TITLE
create a new user from controller

### ISSUE THREAD

**Issue by xxxazxxx** [omniauth/omniauth-identity#49]
I need to create a new user of OMNIAUTH IDENTITY from a controller which accepts email and password along with the controller specific data.

I tried but I could get it to work.

redirect_to("/auth/identity/register?email=" + URI::escape(params["email"]) + "&password="+ URI::escape(params["email"]))

Or something like
Identity.create(:email => params["email"], :password=>params["email"])
session[:authhash] = @authhash
@newuser = User.new  #  from session[:authhash]
Other Processing

**Comment by pboling** [comment]
Your use case doesn't seem to align very well with what this gem is intended for.  Closing.
