### ISSUE TITLE
Disable built-in forms

### ISSUE THREAD

**Issue by svoop** [omniauth/omniauth-identity#50]
When using custom login/registration forms (as shown in Railscast 304), the default forms e.g. on "/auth/identity/register" are still being served. It would be nice to add an option with a path to which these routes are redirected.

A hack is described on Stackoverflow, however, it involves monkey patching and might not be the most future proof solution:

http://stackoverflow.com/questions/8854703/override-auth-identity-page-of-omniauth-identity

Another workaround described elsewhere does something like this:

```
Rails.configuration.middleware.insert_before(Rack::Lock, Rack::Rewrite) do
  rewrite '/auth/identity/register', '/sign_in', method: /get/i
end
```

This won't work with `threadsafe!`, though: ".../actionpack-3.2.13/lib/action_dispatch/middleware/stack.rb:120:in 'assert_index': No such middleware to insert before: Rack::Lock (RuntimeError)"

**Comment by pboling** [comment]
Great solution!
