### ISSUE TITLE
request.env['omniauth.auth'] is always nil when using seperate admin login with identity.

### ISSUE THREAD

**Issue by aman199002** [omniauth/omniauth-identity#51]
I want to use seperate admin login for my application using idenity provider.

I have written this in config/initializers/omniauth.rb

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :identity, :model => Credential, :on_failed_registration =>SessionsController.action(:register)
  provider :identity, :model => Credential, :name => 'admin', :on_failed_registration => SessionsController.action(:login_admin)
  provider :google_oauth2, '000000000.apps.googleusercontent.com', '00000000000'
end
```

In config/routes.rb

```
match '/auth/admin/callback', :to => 'sessions#authenticate_admin'
```

In app/controllers/sessions_controller.rb

```
def authenticate_admin
  auth_hash = request.env['omniauth.auth']
  session[:admin_user] = auth_hash['user_info']['email']
  if admin?
    redirect_to '/'
  else
    render :text => '401 Unauthorized', :status => 401
  end
end
```

But when i try to access request.env['omniauth.auth'], it always gets nil. While it is accessible when using default callback for normal users at sessison#create action. I just want to know if there is anything that has been missed in this code.

**Comment by pboling** [comment]
Hopefully this has been fixed.  If it is still a problem, please try to write a failing spec.
