### ISSUE TITLE
Lack of CSRF token w/ Rails4

### ISSUE THREAD

**Issue by sanemat** [omniauth/omniauth-identity#57]
When redirect to `/auth/:provider/callback`, `omniauth-identity` does not have CSRF token. This brings 2 problems.
- CSRF risk.
- No persist session, like authentication data and `session[:user_id]`, because no CSRF token causes no authentication token.

Below is related issue, and this is very rails-specific code, I also think.
[Adding authenticity token so session will persist](https://github.com/intridea/omniauth/pull/674)

With:
`omniauth-identity v1.1.0`, `rails v4.1(perhaps above v4.0)`

**Comment by pboling** [comment]
Great solution!  This gem will require some customization for many implementations.
