### ISSUE TITLE
how to put length validation on omniauth-identity password field in rails 4

### ISSUE THREAD

**Issue by shaileshgupta** [omniauth/omniauth-identity#59]
Hi, I am trying to put form validations on omniauth-identity in rails 4. However, it is failing continuously with the following error:

["Password can't be blank",
 "Password can't be blank",
 "Password is too short (minimum is 8 characters)"]

My validations look like this in identity.rb

validates :name, presence: true, format: { with: Constants::NAME_REGEX }
validates :email, presence: true, format: { with: Constants::EMAIL_REGEX }  
validates :password, presence: true, length: { minimum: 8 }

Can you point out the mistake or what I may be doing wrong?

**Comment by pboling** [comment]
This gem automatically adds the presence validation, so you do not need to add it again.  You can just add the length validation to be additive with what the gem provides.
