### ISSUE TITLE
Raise if password_confirmation is unnecessarily needed for system actions.

### ISSUE THREAD

**Issue by envygeeks** [omniauth/omniauth-identity#60]
To let the system continue and move on with no indication that the password was and never will be updated if a user does not send "password_confirmation" with `ActiveRecord::Base#update` or `ActiveRecord::Base#update_attributes` is pretty misleading.  There should be some indication rather than nothing at all and a continued update to the database.

**Comment by pboling** [comment]
There is now a validation failure message!  Please try the latest release.
