### ISSUE TITLE
Make omniauth-identity play nicely with multiple authentication

### ISSUE THREAD

**Issue by AndrewFreemantle** [omniauth/omniauth-identity#69]
I've been implementing multiple authentication with different omniauth providers, and while I appreciate the drop-in-and-go simplicity of omniauth-identity, it creates an `Identity` object ([line 63](https://github.com/intridea/omniauth-identity/blob/master/lib/omniauth/strategies/identity.rb#L63)) as part of its registration process that subsequently isn't found by [the multiple providers implementation guide](https://github.com/intridea/omniauth/wiki/Managing-Multiple-Providers) because the creation doesn't populate the `Identity.provider` attribute - _because it doesn't know about it!_

Here's the relevant part of the code from [the guide](https://github.com/intridea/omniauth/wiki/Managing-Multiple-Providers):

```
# app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  def self.find_with_omniauth(auth)
    find_by(uid: auth['uid'], provider: auth['provider'])
  end

  ...

end
```

**Possible fix:** Add an option to tell omniauth-identity that there's a 'provider' attribute on the Identity object and to populate it.

Unless you know another way to make it play a little more seamlessly?  Thanks   :o)

**Comment by mdesjardins** [comment]
:+1: ... I'll probably end up forking and using this patch if it doesn't end up merged soon. :worried:

**Comment by TMaYaD** [comment]
IMHO, Identity itself is a provider and should not concern itself with other providers. The tutorial is a good one with unfortunate naming collision with this gem. I prefer calling the model that holds the 'provider' and 'uid' columns as `Authentication` as per the railscast http://railscasts.com/episodes/235-omniauth-part-1

Shameless self plug: I have extracted the omniauth related stuff from my project into a gem that can be found at https://github.com/LoonyBin/omniauth_boilerplate
It doesn't have much of documentation or tests yet as I do not have time to decouple those from the main app yet. I'll make time if anybody is interested.

**Comment by stevenhaddox** [comment]
@TMaYaD: It's got some work to go, but I've actually been wanting to do pretty much what you've done here for a long time. I've had several apps that use a similar setup for multi-provider & identity provider integration and wanted to abstract them all into a base omniauth gem I could include to generate needed files & integrate multiple side-by-side authentication sources. I'll definitely try and pitch in if I get some cycles!

**Comment by pboling** [comment]
Automatic support for `provider = 'identity'` is now part of this gem!  Thanks @AndrewFreemantle 

Please try out the latest release!

CC @stevenhaddox @TMaYaD @mdesjardins

**Comment by stevenhaddox** [comment]
I completely forgot about this (though I never quite forgot about wanting to try and create that gem I never made time to get the abstraction fully done for). I'm definitely excited to give this a go the next time I add omniauth to a project. Thanks for the work on this @AndrewFreemantle.
