### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nbibler** [omniauth/omniauth-identity#73]
There doesn't appear to be a license defined for this library. I'm assuming it's MIT, since the rest of the Omniauth libraries are ... but there is no reference in the gemspec nor a LICENSE file in the root.

**Comment by jalcine** [comment]
Yeah, and contributing a license feels a bit imposing too. I'm bumping this in hopes one is provided soon.

**Comment by nbibler** [comment]
Agreed regarding a PR with an MIT license. I've done it before for other projects, but it does seem a bit wrong without any prior indication of the intended license from the current authors/maintainers.

**Comment by mhat** [comment]
Submitted https://github.com/intridea/omniauth-identity/pull/75 -- I copied what was done on other projects from Intridia/Michael.

**Comment by jalcine** [comment]
Thanks a lot @mhat!

**Comment by andyroberts** [comment]
This was resolved in 2015 when PR#75 was merged.
