### ISSUE TITLE
Authentication table attributes

### ISSUE THREAD

**Issue by russellseymour** [omniauth/omniauth-identity#88]
This is a very similar issue to #53, but the solution in that issue does not work for me.

I have used the information here https://github.com/intridea/omniauth/wiki/Managing-Multiple-Providers, to setup Identity on my application.

However the code to add the latest auth to the `authentication` table does not add the `provider` or `uid` attributes.

```ruby
  def self.create_with_omniauth(auth)
    create(uid: auth['uid'], provider: auth['provider']) # and other data you might want from the auth hash
  end
```

As suggested in the older issue this might be down to mass assignment.

Is there a quick fix on how to get the `uid` and `provider` set?  The `auth` object does contain this information.

Thanks in advance.

**Comment by pboling** [comment]
This should be fixed now.  Please try the latest release, 3.0.3. https://rubygems.org/gems/omniauth-identity
