### ISSUE TITLE
Show invalid login error

### ISSUE THREAD

**Issue by ryanb** [omniauth/omniauth-identity#9]
When login fails (such as an invalid password) it currently takes the user to the failure callback of the application. I think it would be a much better user experience if mistyping a password allowed the user to stay on the login form with a nice error message saying it's invalid. Isn't this how most providers behave?

**Comment by andyroberts** [comment]
Perhaps this was a problem in 2011 but it's difficult to do with >= v1.1.0.

I suspect it would be good idea to start a wiki to document how to handle common use-cases.

**Comment by pboling** [comment]
Latest release has this feature.
