### ISSUE TITLE
How to limit identity creation per IP

### ISSUE THREAD

**Issue by ShiningBomb** [omniauth/omniauth-identity#90]
I stored identity created per IP, but i don't know how to validate it.
If the validation is in the model, no way i can get the request.ip string.

**Comment by pboling** [comment]
The [latest version of the gem, 3.0.3](https://rubygems.org/gems/omniauth-identity) has an :on_valdiation option, which can be used to implement [a captcha](https://github.com/omniauth/omniauth-identity/pull/86#issue-63225122) and could also be used to validate IP.

Cheers!
