### ISSUE TITLE
How to define authenticated helper in routes.rb to call or access application controller current_user method

### ISSUE THREAD

**Issue by ghost** [omniauth/omniauth-identity#91]
I want to define authenticated root for the application. I am using  [omniauth-identity][1] gem for the authentication and define current_user helper in application controller.  

    def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def current_user=(user)
     session[:user_id] = user.id
    end
And in routes.rb
I want root based on condition

     root to: 'map#index', constraints: Constraints
     root to: 'pages#about'

And within Constraints.rb module defines matches? method

    module Constraints
     def self.matches?(request)
       user = current_user(request)
       return true if user.present?
       false
     end
     def current_user(request)
       @current_user ||= User.find_by_id(request.session[:user_id]) if request.session[:user_id]
     end
    end
And it works fine but the problem duplicate method current_user or we need to check session twice.

In routes we need to pass request object and available locally. so how we can call or pass controller current_user method with request object. Any suggestion so we can define in one place and access it.

It's something similar to devise gem
authenticated and unauthenticated routes helper. 

  [1]: https://github.com/omniauth/omniauth-identity

**Comment by pboling** [comment]
I don't think there is a way to do what you are hoping for, unless you store a hash of the current user in the Rack `env`, setting it in `Constraints`, and then checking for it in the Application Controller.  If you do store it in the Rack `env`, you may want to be careful what attributes get stores.  Perhaps a representation of the user that removes some sensitive data?
