### ISSUE TITLE
Unpermitted parameters: :utf8, :authenticity_token, :auth_key, :password, :commit, :provider

### ISSUE THREAD

**Issue by kul1** [omniauth/omniauth-identity#92]
I upgraded to Rails 5.2 and Ruby 2.5 using omniauth-identity (no devise) and found the error

> Unpermitted parameters: :utf8, :authenticity_token, :auth_key, :password, :commit, :provider

Anyone know how to fix this issue. 
I only found solution most happened the same with acvite_admin which fixed for it but not applicable for this gem.

**Comment by pboling** [comment]
This is an issue of Strong Parameters, which is a feature of Rails.  I am not sure how your issue is related to this gem exactly, but here is the documentation from Rails which explains the Unpermitted Parameters error.

https://edgeapi.rubyonrails.org/classes/ActionController/Parameters.html
