### ISSUE TITLE
Could not find omniauth-identity-1.1.2 in any of the sources

### ISSUE THREAD

**Issue by UbuntuEvangelist** [omniauth/omniauth-identity#94]
this is my GEmfile:
cat Gemfile
source 'https://rubygems.org'

gem 'rails', '~> 4.2'
gem 'rails-i18n'
gem 'responders', '~> 2.0'
gem "better_errors", "~> 2.5.1"

gem "therubyracer"

gem 'puma'
gem 'mysql2', '~> 0.3.21'
gem 'redis-rails'

gem 'rotp', '3.3.1'
gem 'json'
gem 'jbuilder'

gem 'webconsole', '~> 0.2.1'

gem 'padrino'

gem 'omniauth',               '~> 1.8.1'
# gem 'omniauth-identity',      '~> 1.1.1'
gem 'omniauth-identity', '~> 1.1', '>= 1.1.1'
gem 'omniauth-auth0',         '~> 2.0.0'
gem 'omniauth-google-oauth2', '~> 0.5.2'
gem 'omniauth-facebook'

gem 'rucaptcha'
gem 'dalli'

# gem 'invisible_captcha'

gem 'figaro'
gem 'hashie', '~> 3.0'

gem 'aasm', '~> 3.4.0'
# gem 'amqp', '~> 1.3.0'
# gem 'bunny', '~> 2.9.0'
gem 'amqp', '~> 1.8'
gem 'bunny', '~> 2.12'
gem 'cancancan'
gem 'enumerize'
gem 'datagrid'
gem 'kaminari'
gem 'paranoid2'
gem 'active_hash'
gem 'http_accept_language'
gem 'paper_trail', '~> 3.0.1'
gem 'rails-observers'
gem 'country_select', '~> 2.1.0'

gem 'gon', '~> 5.2.0'
gem 'pusher'
gem 'eventmachine', '~> 1.0.4'
gem 'em-websocket', '~> 0.5.1'

gem 'simple_form', '~> 3.1.0'
gem 'slim-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier', '~> 4.1'
gem 'jquery-rails'
gem 'angularjs-rails', '~> 1.3.15'
gem 'bootstrap-sass', '~> 3.2.0.2'
gem 'font-awesome-sass'
gem 'font-awesome-rails'
gem 'bourbon'
gem 'momentjs-rails'
gem 'eco'
gem 'browser', '~> 0.8.0'
gem 'rbtree'
gem 'liability-proof', '0.0.9'
gem 'grape', '~> 1.0.1'
gem 'grape-entity', '~> 0.5.2'
gem 'grape-swagger', '~> 0.27.3'
gem 'grape-swagger-ui', '~> 2.2.8'
gem 'rack-attack', '~> 3.0.0'
gem 'easy_table'
gem 'carrierwave', '~> 1.0'
gem 'fog'
gem 'rest-client', '~> 1.6.8'
gem 'jwt', '~> 1.5'
gem 'email_validator', '~> 1.6'
gem 'clipboard-rails', '~> 1.7'
gem 'god', '~> 0.13.7', require: false
gem 'mini_racer', '~> 0.1', require: false
gem 'arel-is-blank', '~> 1.0'
gem 'sentry-raven', '~> 2.7', require: false
gem 'memoist', '~> 0.16'
gem 'method-not-implemented', '~> 1.0'
# gem 'passgen', '~> 1.0'
gem 'cryptice-passgen', '~> 0.1.2'
gem 'digest-sha3', '~> 1.1'
gem 'cashaddress'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'active_model_otp'
gem 'rqrcode'
gem 'sendgrid'
gem 'phony_rails'
gem 'twilio-ruby'
gem 'bootstrap-datepicker-rails'
gem 'simplebar-rails'
gem 'validates_zipcode'
gem 'chosen-rails'
gem 'httparty'
gem 'fusioncharts-rails', '~> 0.0.2'
gem 'ajax-datatables-rails'
gem 'jquery-datatables'
gem 'useragent'
gem 'geocoder'
gem 'social-share-button', '~> 1.2'
gem 'modernizr-rails'
gem  'grpc'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker', '~> 1.4.3'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'timecop'
  gem 'rspec-rails'
  gem 'pry-byebug'
  gem 'rubocop', '~> 0.58.2', require: false
  gem 'rubocop-rspec'
end

group :test do
  gem 'database_cleaner'
  gem 'mocha', require: false

  gem 'capybara',            '~> 2.17'
  gem 'selenium-webdriver',  '~> 3.8'
  gem 'chromedriver-helper', '~> 1.1'
  gem 'rack_session_access', '~> 0.1'
end

when i run :
sudo bundle install

it shows Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Could not find omniauth-identity-1.1.2 in any of the sources
![Screenshot from 2019-10-05 02-08-48](https://user-images.githubusercontent.com/1058663/66236725-15591580-e715-11e9-8a27-fbcbd2583207.png)

**Comment by andyroberts** [comment]
[v1.1.12](https://rubygems.org/gems/omniauth-identity/versions/1.1.2) was yanked due to being [compromised](https://github.com/omniauth/omniauth-identity/issues/93). You'll have to update your Gemfile.lock to use v1.1.1.
