### ISSUE TITLE
Any chance of a new release (1.1.13)?

### ISSUE THREAD

**Issue by andyroberts** [omniauth/omniauth-identity#96]
Obviously v1.1.12 was a phoney release. And I know that there hasn't been much activity on this gem for a while. However, a release based on master would at least resolve the bcrypt gem dependency warning.

PS I'm happy to volunteer a bit of time assisting with this gem if you need a hand. My company depends on this gem so would be willing to contribute a bit of time to maintain.

**Comment by pboling** [comment]
> I'm happy to volunteer a bit of time assisting with this gem if you need a hand. My company depends on this gem so would be willing to contribute a bit of time to maintain.

*Same here!*

Would love to help maintain this gem. @omniauth @BobbyMcWho @bufferoverflow @md5 @supernova32 @tmilewski @toupeira

I took over the [oauth2](https://rubygems.org//gems/oauth2) gem a couple years ago, and would be happy to keep this one going as well.

Can someone add @andyroberts and @pboling (me) to the org, or at least this repo, and also give me push rights on rubygems.org?

**Comment by BobbyMcWho** [comment]
@mbleigh and @tmilewski are the owners of the gem on rubygems, only they have access to add you for that. 

I'm not entirely sure who has write access to this specific repo, but I am not one of the maintainers of this specific project.

**Comment by pboling** [comment]
I've emailed @mbleigh but he's pretty busy it seems.  Until things change around here, it's a fork.

**Comment by pboling** [comment]
@mbleigh @tmilewski 

Fork is:
https://github.com/rivierapartners/omniauth-identity/tree/modernize

Pull Request:
https://github.com/omniauth/omniauth-identity/pull/99

**Comment by bufferoverflow** [comment]
Who could should maintain this?

It does only make sense to assign rights on the repo if owner of the gem on rubygems is not inline.
I can only manage right on the github omniauth organization I've created a while ago, but not for specific rubygems.

I think as soon as new maintainers are identified, @mbleigh and @tmilewski can manage rubygems push permissions.

**Comment by pboling** [comment]
@bufferoverflow I volunteer to maintain this gem, and be a part of the omniauth org if that's desirable.  It appears that the main omniauth gem needs some love also.

**Comment by andyroberts** [comment]
To anyone looking at this issue hoping for news of an updated version of this gem... May I point you to a new fork, [omniauth-identity2](https://github.com/Jellybooks/omniauth-identity2), that aims to keep the Omniauth Identity strategy up-to-date whilst maintaining compatibility (as mush as possible):

https://github.com/Jellybooks/omniauth-identity2

The first release includes @pboling's "[Modernize it](https://github.com/omniauth/omniauth-identity/pull/99)" pull request, and is available to include in your projects via RubyGems: https://rubygems.org/gems/omniauth-identity2

I also like the [PR "add on_validation options for validation something like captcha"](https://github.com/omniauth/omniauth-identity/pull/86) by @Freeza91 and I will investigate adding that feature next because it aligns with similar functionality I'd like to see made easily achievable with this strategy. I will over time investigate all the upstream open issues and PRs to see what is relevant for omniauth-identity2 and resolve accordingly.

New issues and PRs are **very welcome** over at [omniauth-identity2](https://github.com/Jellybooks/omniauth-identity2). I want to keep expectations realistic: I'm busy with work and family life, so this gem isn't my no 1 priority, but equally I don't expect it to be terribly busy either, and I will at least *respond* to comments as promptly as possible even if it takes a little while to make code changes.

In case anyone is wondering, why not simply contribute/offer to maintain the omniauth-identity repository rather than forking, you'll see in the above thread efforts were made but to no avail. IMHO, for the short-term, the only realistic option of keeping this functionality alive is through an active fork that interested parties can coalesce around.

cc @mbleigh @tmilewski @pboling @bufferoverflow

**Comment by bufferoverflow** [comment]
@mbleigh and @tmilewski Seeing another fork because you do not like to provide push rights for the gem was not the idea I had in mind when creating the omniauth organization on Github . I still believe that assigning maintainer rights to @andyroberts makes sense, so he could push the gem. I can of course add rights for the repo as suggested.

**Comment by mbleigh** [comment]
@pboling @andyroberts I'm happy to make you both maintainers of the gem, please let me know what email addresses to use. Sorry folks, I know I'm slow getting back on these things but I haven't maintained a Ruby codebase in > 5 years at this point and I don't always notice these things come through.

**Comment by bufferoverflow** [comment]
Thanks @mbleigh !

I just added @pboling and @andyroberts to the team https://github.com/orgs/omniauth/teams/omniauth-identity-maintainers

**Comment by mbleigh** [comment]
@andyroberts you now have publish on the gem.

**Comment by andyroberts** [comment]
Many thanks @bufferoverflow and @mbleigh.

Open source can be slow and frustrating at times. We're all grateful for the time and energy maintainers, bug reporters, contributors etc, make to a project. It's thanks to open source that I could even contemplate a fork. I wasn't aiming for a hostile takeover or trying to force someone's hand. It's a first-world problem, IMHO, that the upstream repo isn't as up-to-date as I'd like. We don't know what's going on in maintainers' lives. I just wanted to get some momentum back in the project and was happy to take the lead.

Of course, I'm very pleased that I can now contribute directly to the repository and the thousands of existing omniauth-identity users can benefit from regular maintenance without having to think too much about how/where to obtain other than an occasional `bundle update`.  Hopefully @pboling will accept the invite too so that there are a couple of sets of eyes on the code, issues and PRs. 😀

**Comment by mbleigh** [comment]
I'm grateful for all the folks who have picked up the torch on projects I started many years ago but don't have time to maintain. It's always a relief to feel like something that is important and useful to many is in good hands. Thanks for stepping up, and best of luck!

**Comment by andyroberts** [comment]
FYI To anyone who now wants an **on-topic** response to this issue ("Any chance of a new release (1.1.13)")! I now get to resolve my own question.

Before this week is over I'll merge PR #99 and then release version 2.0 of this gem. It's going straight to v2.0 because it's a slight breaking change due to the dropping of direct MongoMapper support (another casualty in the list of unmaintained projects that creates an unresolvable gem version conflict between MongoMapper and Mongoid -- the latter takes priority because it's more commonly used and still actively maintained.)

**Comment by pboling** [comment]
@andyroberts I am happy to start contributing here!  This is a gem that I actively use for work, and I need it to remain functional, and I am having trouble with it *right now*, so I am happy to dig in.

@mbleigh If there are other projects from your Ruby days that are languishing in dusty corners, I would be happy to shepherd them until I can get more volunteers to take over.  I am still heavily involved in Ruby.  HMU peter.boling@gmail.com

**Comment by mbleigh** [comment]
@pboling you have publish for `omniauth-identity` now as well, and thanks for the offer. I'm quite certain there are other projects languishing in dusty corners, but I'm not aware of any others with people actively clamoring for new releases that don't already have new owners of some kind.

**Comment by pboling** [comment]
Version 2.0.0 was released by @andyroberts.  This issue can be closed now!

Although I now have push rights to rubygems, I don't have any rights on the repo here. @andyroberts Are you able to grant me rights here?

https://rubygems.org/gems/omniauth-identity/versions/2.0.0

**Comment by andyroberts** [comment]
> Although I now have push rights to rubygems, I don't have any rights on the repo here. @andyroberts Are you able to grant me rights here?

I don't have those permissions. @bufferoverflow said he'd added you. (https://github.com/omniauth/omniauth-identity/issues/96#issuecomment-683924373) I can't recall if the onboarding happened automatically or whether you had to accept an invite. If the latter than you'll probably have to ask him again.

**Comment by pboling** [comment]
I have searched my email, and not found any kind of invite related to this repository.  @bufferoverflow Can you try adding me to the org or the repo again?

**Comment by bufferoverflow** [comment]
@pboling done, just added you to https://github.com/orgs/omniauth/teams/omniauth-identity-maintainers
